//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RervRoomDate
    {
        public System.Guid Id { get; set; }
        public System.Guid RoomId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
